"""Render the actual PowerPoint with LibreOffice and validate/export its slide images."""
import hashlib,json,os,shutil,subprocess,tempfile,time
from pathlib import Path
from pptx import Presentation
from pypdf import PdfReader
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'results/presentation';G=OUT/'gallery'
lo=os.environ.get('CHRNA_LIBREOFFICE_BIN') or shutil.which('libreoffice') or shutil.which('soffice')
ppm=os.environ.get('CHRNA_PDFTOPPM_BIN') or shutil.which('pdftoppm')
if not lo or not ppm:raise SystemExit('Actual PPTX rendering requires LibreOffice and pdftoppm; shared-source SVG/PNG/PDF exports are generated by build_gallery.py.')
env=os.environ.copy();env['SAL_USE_VCLPLUGIN']='svp'
if os.environ.get('CHRNA_RENDER_LIBRARY_PATH'):env['LD_LIBRARY_PATH']=os.environ['CHRNA_RENDER_LIBRARY_PATH']
profile=Path(tempfile.mkdtemp(prefix='chrna-lo-profile-'))
cmd=[lo,f'-env:UserInstallation={profile.as_uri()}','--headless','--norestore','--nofirststartwizard','--convert-to','pdf','--outdir',str(OUT),str(OUT/'chRNA_gallery.pptx')]
start=time.time()
for attempt in range(3):
 result=subprocess.run(cmd,env=env,capture_output=True,text=True,timeout=120)
 if result.returncode not in (0,81):raise RuntimeError(result.stdout+'\n'+result.stderr)
 if (OUT/'chRNA_gallery.pdf').exists() and (OUT/'chRNA_gallery.pdf').stat().st_mtime>=start:break
else:raise RuntimeError('LibreOffice did not write a fresh PDF.')
print(result.stdout.strip())
dest=G/'pptx_render';dest.mkdir(exist_ok=True)
subprocess.run([ppm,'-png','-r','100',str(OUT/'chRNA_gallery.pdf'),str(dest/'slide')],env=env,check=True,timeout=120)
slides=Presentation(OUT/'chRNA_gallery.pptx').slides;pdf=PdfReader(OUT/'chRNA_gallery.pdf')
assert len(slides)==len(pdf.pages)==12
for slide in slides:
 assert len(slide.shapes)>=20
 assert slide.has_notes_slide
assert '2,000,000' in pdf.pages[8].extract_text()
assert '0.296' in pdf.pages[6].extract_text() and '0.300' in pdf.pages[6].extract_text()
assert '48.70' in pdf.pages[3].extract_text()
files=sorted(dest.glob('slide-*.png'));assert len(files)==12
canvas=Image.new('RGB',(1600,1280),(225,228,234));draw=ImageDraw.Draw(canvas)
for i,f in enumerate(files):
 im=Image.open(f).convert('RGB');im.thumbnail((500,281));x=20+(i%3)*530;y=15+(i//3)*320;canvas.paste(im,(x,y));draw.text((x,y+285),f'Slide {i+1:02} · actual PowerPoint render',fill='black')
canvas.save(OUT/'gallery_contact_sheet.png')
report={'status':'passed','slides':len(slides),'render_method':'Actual PPTX converted by LibreOffice; PDF pages rendered by pdftoppm at 100 dpi.','checks':['12 slides/PDF pages/images','editable shape-rich slides','source/method/caveat notes on every slide','actual PDF contains reviewed AP values, pilot input count and low-confidence value'],'pptx_sha256':hashlib.sha256((OUT/'chRNA_gallery.pptx').read_bytes()).hexdigest(),'pdf_sha256':hashlib.sha256((OUT/'chRNA_gallery.pdf').read_bytes()).hexdigest(),'render_command':cmd[:1]+['-env:UserInstallation=<temporary-profile>']+cmd[2:]}
(G/'render_validation.json').write_text(json.dumps(report,indent=2));print('Actual PowerPoint render validation passed.')
