const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const projectRoot=path.resolve(__dirname,'..');
const appRoot=path.join(projectRoot,'demos/chimera-dashboard');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true}); const errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.CHRNA_DEMO_URL || 'http://127.0.0.1:4173/',{waitUntil:'networkidle'});
 const body=()=>page.locator('body').innerText();
 const choose=async(label,text)=>{await page.getByRole('button',{name:new RegExp(label)}).click();await page.getByText(text,{exact:true}).last().click();};
 for(let i=1;i<=6;i++) assert.equal(await page.locator(`#ch-step-${i}`).count(),1);
 assert.match(await body(),/Illustrative demo — fictional evidence/);checks.push('All six sections render with explicit synthetic disclosure');
 await page.getByRole('button',{name:'Compare parents',exact:true}).nth(1).click();assert.match(await page.locator('#ch-step-5').innerText(),/Reject in this scenario/);assert.match(await page.locator('#ch-step-5').innerText(),/Illustrative cross-reactivity/);
 await page.getByRole('button',{name:'Compare parents',exact:true}).nth(2).click();assert.match(await page.locator('#ch-step-5').innerText(),/Hold: incomplete screens/);checks.push('Parent cross-reactivity rejects; missing screens remain on hold');
 await page.getByRole('switch',{name:'Assume orthogonal protein detection'}).click();
 await choose('Assumed localization','Accessible cell surface');assert.match(await page.locator('.ch-verdict').innerText(),/Explore a junction binder/);
 await page.getByRole('button',{name:'Reset assumptions'}).click();assert.match(await page.locator('.ch-verdict').innerText(),/Validate the RNA junction first/);checks.push('Scenario assumptions update decisions and reset without changing observations');
 await choose('Explore modality','Small molecule');assert.match(await page.locator('#ch-step-3').innerText(),/defensible pocket/);
 await choose('Explore modality','RNA-directed reagent');assert.match(await page.locator('#ch-step-3').innerText(),/both parental transcripts/);checks.push('All modality views render their prerequisites');
 await choose('Evidence set','K562 · not yet run');assert.match(await body(),/K562 analysis has not been executed/);assert.doesNotMatch(await body(),/SIM-B0/);assert.match(await body(),/No generated molecules or binders available/);checks.push('Unexecuted K562 view retains missing evidence and excludes synthetic designs');
 await choose('Evidence set','Mouse pilot · real results');assert.match(await body(),/Wiz → Cmtm3/);assert.doesNotMatch(await body(),/SIM-B0/);
 await choose('Candidate','Rab2a → Lyn');assert.match(await page.locator('.ch-candidate').innerText(),/Rab2a → Lyn/);
 await page.getByText(/Inspect amino-acid hypothesis/).click();assert.match(await page.locator('.ch-sequence').innerText(),/^MAYAYL/);checks.push('Real candidate switching changes exact record and sequence; synthetic designs remain absent');
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export decision brief',exact:true}).click();const download=await downloadPromise;const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(exported.candidate.parentA,'Rab2a');assert.equal(exported.actualGenerationPerformed,false);assert.equal(exported.designRecords.length,0);checks.push('Export contains selected real candidate and no fictional designs');
 await choose('Evidence set','Illustrative demo');
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(appRoot,'preview-mobile.png'),fullPage:false});
 const geometry=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(geometry.scroll<=geometry.width+1,JSON.stringify(geometry));checks.push('390 px mobile view has no page-level horizontal overflow');
 await page.setViewportSize({width:1440,height:1050});await page.screenshot({path:path.join(appRoot,'preview-desktop.png'),fullPage:true});assert.equal(errors.length,0);
 const result={checkedAt:new Date().toISOString(),checks,pageErrors:errors,status:'passed'};fs.writeFileSync(path.join(appRoot,'browser-checks.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
