function selectedOrf(){return current().reconstruction?.orfs?.[0];}
function proteinView(){
 const o=selectedOrf(),svg=$('k562-protein-track');if(!o){svg.replaceChildren();return;}const w=Math.max(240,svg.getBoundingClientRect().width),cell=(w-24)/o.protein.length;svg.replaceChildren();svg.setAttribute('viewBox',`0 0 ${w} 70`);
 const t=current().arms[active].transcripts[tx[active]],e=t?.exons[ex[active]],chosen=+$('k562-residue').value||0;
 o.residues.forEach((r,i)=>{const refs=r.bases.flatMap(b=>b.reference_assignments),arms=[...new Set(refs.map(v=>v.arm))],shared=arms.length>1,matching=e&&refs.some(v=>v.arm===active&&v.position>=e.start&&v.position<e.end);mark(svg,'rect',{x:12+i*cell,y:12,width:Math.max(1,cell-0.6),height:20,fill:`var(--viz-series-${shared?3:arms.length?arms[0]+1:4})`,opacity:matching?1:0.3});if(i===chosen)mark(svg,'path',{d:`M ${12+i*cell+cell/2} 37 l -4 7 h 8 Z`,fill:'var(--foreground)'});});mark(svg,'text',{x:12,y:62},'1');mark(svg,'text',{x:w-12,y:62,'text-anchor':'end'},`${o.protein.length} aa · provisional`);
 const count=e?o.residues.filter(v=>v.bases.some(b=>b.reference_assignments.some(ref=>ref.arm===active&&ref.position>=e.start&&ref.position<e.end))).length:0; $('k562-exon-detail').textContent=$('k562-exon-detail').textContent.split(' · Hypothetical residue contribution:')[0]+' · Hypothetical residue contribution: '+count+' (provisional ORF).';
 const r=o.residues[chosen],labels=[];for(const b of r.bases){let origins=[];for(const ref of b.reference_assignments){const arm=current().arms[ref.arm],tr=arm.transcripts[tx[ref.arm]],ee=tr?.exons.filter(e=>e.start<=ref.position&&ref.position<e.end)||[];origins.push(`${arm.gene} ${ee.length?ee.map(e=>'E'+e.n).join('/'):'non-exonic in this reference choice'} (${tr?.id||'unknown transcript'})`);}labels.push(`RNA base ${b.rna_position}: ${origins.join(' + ')||'unassigned join base'}`);}
 $('k562-residue-detail').textContent=`Residue ${r.residue} ${r.aa} · ${labels.join('; ')} · structural confidence: unavailable`;
}
function followupView(){const c=D.candidates[ci],r=current(),rec=r.reconstruction,s=c.extension,origin=c.origin;
 const rows=[['RNA reconstruction',`${s.qualifying_reads_reconstructed} qualifying reads processed across A/B`],['Complete spanning ORF',`${s.observed_complete_spanning_ORF_reads} observed-read / ${s.reference_assisted_complete_spanning_ORF_reads} reference-assisted ORF-bearing reads`],['Structure prediction','Deferred: '+s.folding_reasons.join('; ').replaceAll('_',' ')],['Adapter-core / poly(A/T) flags',`${origin.internal_adapter_flagged_reads} / ${origin.internal_polyAT_flagged_reads} among ${origin.assessed_reads} assessed reads; sequence screen only`],['RNA-origin assessment',origin.origin_geometry+'; mechanism unresolved'],['Same-culture DNA / biological independence','Unavailable / unknown']];$('k562-followup').replaceChildren(...rows.map(row=>{const tr=el('tr');tr.append(el('th',{},row[0]),el('td',{},row[1]));return tr;}));
 const oi=c.reads.findIndex(v=>v.reconstruction?.orfs.length);$('k562-orf-read').hidden=oi<0;$('k562-orf-read').onclick=()=>{ri=oi;tx=[0,0];ex=[0,0];active=0;$('k562-read').value=String(ri);renderRead();save();};
 $('k562-rna-sequences').textContent=rec?`Read ${r.id}\nObserved RNA (${rec.observed_rna.length} nt; uncorrected)\n${rec.observed_rna}\n\nReference-assisted provisional RNA (${rec.reference_assisted_rna.length} nt)\n${rec.reference_assisted_rna}\n\nCorrection events: ${rec.correction_events}\nSequence issues: ${JSON.stringify(rec.unresolved_sequence_reasons)}\nNMD: ${rec.nmd}\nSHA256: ${rec.rna_sha256}`:'Not reconstructed: this read did not meet the frozen RNA support criteria.';
 const o=selectedOrf();$('k562-orf-panel').hidden=!o;if(o){$('k562-orf-status').textContent=`${o.protein.length}-aa reference-assisted hypothesis · unresolved sequence · not eligible for folding · protein existence unknown`;options($('k562-residue'),o.residues.map(v=>`${v.residue} · ${v.aa}`));$('k562-residue').onchange=proteinView;proteinView();}else{$('k562-residue-detail').textContent='';$('k562-protein-track').replaceChildren();}
}
