#!/usr/bin/env python3
"""Write a concise final compute receipt from verified artifacts and confirmed stop."""
import argparse,json
from pathlib import Path
from datetime import datetime,timezone
from structure_campaign_stage import save,digest
p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);a=p.parse_args();root=a.output
jobs=json.loads((root/'jobs.json').read_text());cleanup=json.loads((root/'cleanup_receipt.json').read_text());assert cleanup['status']=='stopped_confirmed'
attempted=[j for j in jobs if j.get('attempts') and j['status']!='cached_verified'];actual=[j for j in jobs if j['status']=='verified'];cached=[j for j in jobs if j['status']=='cached_verified'];first=[j for j in actual if j['seed']==20260919];extra=[j for j in actual if j['seed']!=20260919]
assert not any(j['status']=='running'for j in jobs)
summary=json.loads((root/'summary.json').read_text());gallery=json.loads((root/'structure_gallery.json').read_text())
receipt={'status':'completed_and_owned_gpu_stopped','utc':datetime.now(timezone.utc).isoformat(),'scientific_scope':'Conditional reference-derived ORF sensitivity characterization; strict primary protein eligibility remains zero. RNA assay support does not validate full ORFs, translation, folding or function.','protocols':summary['protocols'],'new_first_pass_candidate_models':sum(j['role']in {'primary','sensitivity'}for j in first),'new_first_pass_control_models':sum(j['role']in {'control','reference_control'}for j in first),'new_diagnostic_seed_models':len(extra),'diagnostic_unique_peptides':len({j['sequence_sha256']for j in extra}),'new_models_total':len(actual),'prior_models_reused_as_separate_msa_context':len(cached),'unique_new_modeled_sequences':len({j['sequence_sha256']for j in actual}),'new_model_attempts_total':sum(len(j.get('attempts',[]))for j in attempted),'new_prediction_process_wall_seconds_sum':sum(j.get('wall_seconds',0)for j in attempted),'rendered_gallery_assets':len(gallery['assets']),'external_msa_sequences_uploaded':0,'hosted_nvidia_nim_invocations':0,'cleanup_and_cost':cleanup,'artifact_sha256':{name:digest(root/name)for name in ['jobs.json','model_metrics.tsv','summary.json','structure_gallery.json','cleanup_receipt.json']},'limitations':['Single-sequence Boltz2 protocol is explicitly separate from the preferred MSA-backed protocol and may reduce accuracy.','No experimentally validated full-protein primary cohort was available. Selection is descriptive, not an estimate of all chRNA prevalence.','pLDDT is model confidence, not an experimental disorder or function measurement.','Observed process timings and sampled GPU maxima do not constitute a speedup benchmark or forecast of cold setup/MSA workloads.','GPU charge is elapsed time multiplied by the live quote, not a reconciled provider invoice; unmeasured storage/egress remains unknown.']}
save(root/'campaign_receipt.json',receipt);print(json.dumps({k:receipt[k]for k in ['status','new_first_pass_candidate_models','new_first_pass_control_models','new_diagnostic_seed_models','new_models_total','new_prediction_process_wall_seconds_sum']},indent=2))
